/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cardgame;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class AppTest {

    @Test
    public void shouldReturnTrue() {
        assertTrue(true);
    }
}
