/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CardGame;


import CardGame.ClassiCarte.CartaNapoletana;
import CardGame.ClassiCarte.CartaNapoletana.Seme;




public class App<Napoletana> {
    public String getGreeting() {
        return "Hello World!";
    }

    CartaNapoletana<Napoletana> cartaNaple1 =  new CartaNapoletana<Napoletana>(Seme.BASTONI, 10);
    

}