/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CardGame;

import javax.swing.plaf.basic.BasicButtonUI;

import CardGame.Napoletana;
import CardGame.Napoletana.Seme;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    Carta<Napoletana> cartaNaple1 =  new Carta<Napoletana>(new Napoletana(Seme.BASTONI, 10));

    

}